### ISSUE TITLE
qaeval setup issue

### ISSUE THREAD

**Issue by amberhuang01** [danieldeutsch/sacrerouge#120]
Hi Daniel,

I notice this happens occasionally when setting up qaeval. Any idea what might be the issue?
![Capture](https://user-images.githubusercontent.com/45579448/131593444-41669857-5769-4e41-85e8-6f8ddf3042fd.JPG)

Cheers,
Amber

**Comment by danieldeutsch** [comment]
Hi,

I've occasionally had problems with Google Drive when I download multiple files one after the other. Could you try manually downloading the file from [here](https://drive.google.com/file/d/1q2Z3FPP9AYNz0RJKHMlaweNhmLQoyPA8/view)? It is also stored [here](https://cogcomp.seas.upenn.edu/models/qaeval-experiments/qa-model.zip), which shouldn't have download issues.

If that fixes the problem, I'll change the Google Drive pointers to the ones hosted on Penn's servers.

**Comment by saiprabhakar** [comment]
I can confirm that this is the issue is happening again, I cant find any solution to getting around the "too large to do virus scan" warning from google.
Solutions can be:
1. We can point to your univ server as you mentioned, or
2. We can display which link to download the files from manually (from the drive) in the error message.

**Comment by danieldeutsch** [comment]
Very frustrating! Thanks for letting me know. I wish there was a more reliable way to download files from Google Drive. I will move the models to a different location and update the links.

**Comment by danieldeutsch** [comment]
I merged the fix. Also, if you have Docker installed or can install it on the machine where the code is running, [this](https://repro.readthedocs.io/en/latest/models/deutsch2021.html) implementation of the metric is likely far easier to use since all of the dependencies are isolated within the Docker container.
